# Generated by Django 3.2.9 on 2022-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220211_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcmovies',
            name='janr',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
