# Generated by Django 3.2.9 on 2022-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upcmovies_janr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blogmain/')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('like', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
