# Generated by Django 3.2.9 on 2022-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogmain_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Ind/')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('like', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
