# Generated by Django 3.2.9 on 2022-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind',
            name='janr',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ind',
            name='link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
