# Generated by Django 3.2.9 on 2022-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220217_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
